### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by yy9568** [yuandong-tian/Document-Rectification--CVPR11-#3]
Hi, the links are invalid now, can you share files again? Thank you!
`--2019-11-03 12:17:52--  https://www.dropbox.com/sh/yx0cdpe88c4folq/AABV8P5Qzm12_y-R7s0qX0uya/camera_ready_smallimages.mat?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 69.171.230.18
Connecting to www.dropbox.com (www.dropbox.com)|69.171.230.18|:443... failed: Connection timed out.`

**Comment by yy9568** [comment]
@yuandong-tian

**Comment by vinayak-pathak** [comment]
@yuandong-tian Hi,  please share the  files ..

**Comment by vinayak-pathak** [comment]
PLease Please!!

**Comment by wangyl218** [comment]
PLease Please!!

**Comment by pryy** [comment]
Could you please share the files?

**Comment by damallett** [comment]
@wangyl218 @vinayak-pathak @zhouyuangan Did you ever get any files or sort through it to be able to run the code without it?

**Comment by yy9568** [comment]
> @wangyl218 @vinayak-pathak @zhouyuangan Did you ever get any files or sort through it to be able to run the code without it?

No, I didn't. The file is needed.

**Comment by TiffanyXYf** [comment]
@yuandong-tian @vinayak-pathak 
Could you please share the two .mat files again?
